# Utiliser une image Python
FROM python:3.10

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers du projet
COPY . /app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port de Django (modifie si nécessaire)
EXPOSE 8000

# Commande pour démarrer le serveur Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
